// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_NAME: "boatlists";
	RP_ID: "boatlists.dtegart78.workers.dev";
	SECRET_KEY: string;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	DB: D1Database;
	ASSETS: Fetcher;
}
